server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Finance
    username: root
    password: a4s5d6A4s5!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create    # update
    show-sql: true        # 실행되는 쿼리 출력
    properties:
      hibernate:
        format_sql: true   # 쿼리 보기 좋게 포맷팅
        use_sql_comments: true  # 어떤 엔티티에서 나온 쿼리인지 주석 추가됨
    database-platform: org.hibernate.dialect.MySQL8Dialect